#ifndef MODE_H
#define	 MODE_H 
//             0       1                2        3         4                5               6           
enum MODE { IDLE, IDLE_PISTOL, IDLE_RIFLE, IDLE_SHOTGUN, MOVING, MOVING_PISTOL, MOVING_RIFLE, MOVING_SHOTGUN, SHOOTING, SHOOTING_PISTOL, SHOOTING_RIFLE, SHOOTING_SHOTGUN, ZOMBIE_WALK, ZOMBIE_RUN, ZOMBIE_ATTACK, IDLE_FEET, MOVING_FEET, IDLE_TURRET, SHOOTING_TURRET };

#endif
